create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null default 'site',
  created_at timestamptz not null default now()
);

create index if not exists subscribers_created_at_idx on public.subscribers (created_at desc);
alter table public.subscribers enable row level security;

create table if not exists public.sponsor_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists sponsor_leads_created_at_idx on public.sponsor_leads (created_at desc);
alter table public.sponsor_leads enable row level security;
