import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SubscribeForm } from "@/components/SubscribeForm";
import { articles, getArticle } from "@/data/content";
import { formatDate, topicName } from "@/lib/content";
export async function generateStaticParams(){ return articles.map(({slug})=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const article=getArticle(slug); return article ? {title:article.title,description:article.dek,openGraph:{title:article.title,description:article.dek,type:"article",publishedTime:article.publishedAt}} : {}; }
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const article=getArticle(slug); if(!article) notFound(); return <article className="articlePage"><div className="shell"><header className="articleHeader"><div className="articleMeta"><span className="pill">{article.category}</span><Link href={`/topics/${article.topic}`}>{topicName(article.topic)}</Link></div><h1>{article.title}</h1><p className="articleDek">{article.dek}</p></header><div className="articleLayout"><aside className="articleAside"><strong>Published</strong>{formatDate(article.publishedAt)}<br/><br/><strong>Reading time</strong>{article.readTime} minutes<br/><br/><strong>Tags</strong>{article.tags.join(" · ")}</aside><div className="articleBody">{article.body.map((section,index)=><section key={index}>{section.heading && <h2>{section.heading}</h2>}{section.paragraphs.map((paragraph,pIndex)=><p key={pIndex}>{paragraph}</p>)}{section.code && <pre className="codeBlock"><code>{section.code}</code></pre>}</section>)}</div><aside className="articleRail"><h3>Stay in the loop</h3><p>Get the next builder signal before it disappears into your feed.</p><SubscribeForm compact source={`article:${article.slug}`}/></aside></div></div></article>; }
